# Import

In [1]:
import os
import json
from lxml import etree
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
INPUT_DIR = os.path.join("..", "input")
TEMP_DIR = os.path.join("..", "temp")
FLIGHTS_CSV = os.path.join(INPUT_DIR, "flights.csv")
AIRPORTS_CSV = os.path.join(INPUT_DIR, "airports.csv")
PLANES_CSV = os.path.join(INPUT_DIR, "planes.csv")
AIRLINES_XML = os.path.join(INPUT_DIR, "airlines.xml")
WEATHER_JSON = os.path.join(INPUT_DIR, "weather.json")
TRAIN_PICKLE = os.path.join(TEMP_DIR, "train.pickle")
TEST_PICKLE = os.path.join(TEMP_DIR, "test.pickle")

## Import flights.csv

In [3]:
flights_df = pd.read_csv(FLIGHTS_CSV)

In [4]:
flights_df.head()

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

## Import airports.csv

In [5]:
airports_df = pd.read_csv(AIRPORTS_CSV)

In [6]:
airports_df.head()

,Unnamed: 0,faa,name,lat,lon,alt,tz,dst,tzone
0,0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York

## Import planes.csv

In [7]:
planes_df = pd.read_csv(PLANES_CSV)

In [8]:
planes_df.head()

,Unnamed: 0,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,3,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,4,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan

## Import weather.json

In [9]:
with open(WEATHER_JSON, "r", encoding="utf-8") as f:
    weather_json = json.load(f)

In [10]:
weather_df = pd.DataFrame(weather_json)

In [11]:
weather_df.head()

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,EWR,2013,1,1,1,39.02,26.06,59.37,270.0,10.35702,NaN,0.0,1012.0,10.0,2013-01-01T06:00:00Z
1,EWR,2013,1,1,2,39.02,26.96,61.63,250.0,8.05546,NaN,0.0,1012.3,10.0,2013-01-01T07:00:00Z
2,EWR,2013,1,1,3,39.02,28.04,64.43,240.0,11.50780,NaN,0.0,1012.5,10.0,2013-01-01T08:00:00Z
3,EWR,2013,1,1,4,39.92,28.04,62.21,250.0,12.65858,NaN,0.0,1012.2,10.0,2013-01-01T09:00:00Z
4,EWR,2013,1,1,5,39.02,28.04,64.43,260.0,12.65858,NaN,0.0,1011.9,10.0,2013-01-01T10:00:00Z

## Import airlines.xml

Struktur der Datei:

```xml
<airlines>
  <airline carrier="9E">Endeavor Air Inc.</airline>
  <airline carrier="AA">American Airlines Inc.</airline>
  <airline carrier="AS">Alaska Airlines Inc.</airline>
</airlines>
```

In [12]:
airlines_tree = etree.parse(AIRLINES_XML)

In [13]:
airlines_root = airlines_tree.getroot()

In [14]:
rows = []

In [15]:
for a in airlines_root.findall("airline"):
    row = a.attrib
    row["name"] = a.text
    rows.append(row)

In [16]:
rows

[{'carrier': '9E', 'name': 'Endeavor Air Inc.'},
 {'carrier': 'AA', 'name': 'American Airlines Inc.'},
 {'carrier': 'AS', 'name': 'Alaska Airlines Inc.'},
 {'carrier': 'B6', 'name': 'JetBlue Airways'},
 {'carrier': 'DL', 'name': 'Delta Air Lines Inc.'},
 {'carrier': 'EV', 'name': 'ExpressJet Airlines Inc.'},
 {'carrier': 'F9', 'name': 'Frontier Airlines Inc.'},
 {'carrier': 'FL', 'name': 'AirTran Airways Corporation'},
 {'carrier': 'HA', 'name': 'Hawaiian Airlines Inc.'},
 {'carrier': 'MQ', 'name': 'Envoy Air'},
 {'carrier': 'OO', 'name': 'SkyWest Airlines Inc.'},
 {'carrier': 'UA', 'name': 'United Air Lines Inc.'},
 {'carrier': 'US', 'name': 'US Airways Inc.'},
 {'carrier': 'VX', 'name': 'Virgin America'},
 {'carrier': 'WN', 'name': 'Southwest Airlines Co.'},
 {'carrier': 'YV', 'name': 'Mesa Airlines Inc.'}]

In [17]:
airlines_df = pd.DataFrame(rows)

In [18]:
airlines_df

   carrier                         name
0       9E            Endeavor Air Inc.
1       AA       American Airlines Inc.
2       AS         Alaska Airlines Inc.
3       B6              JetBlue Airways
4       DL         Delta Air Lines Inc.
5       EV     ExpressJet Airlines Inc.
6       F9       Frontier Airlines Inc.
7       FL  AirTran Airways Corporation
8       HA       Hawaiian Airlines Inc.
9       MQ                    Envoy Air
10      OO        SkyWest Airlines Inc.
11      UA        United Air Lines Inc.
12      US              US Airways Inc.
13      VX               Virgin America
14      WN       Southwest Airlines Co.
15      YV           Mesa Airlines Inc.

## Merge 1: flights + planes

In [19]:
flights_df.shape

(336776, 20)

In [20]:
planes_df.shape

(3322, 10)

In [21]:
merged_df = pd.merge(
    flights_df.drop("Unnamed: 0", axis=1),
    planes_df.drop("Unnamed: 0", axis=1),
    on="tailnum",
    suffixes=["", "_plane"],
    how="left",
)

In [22]:
merged_df.shape

(336776, 27)

In [23]:
merged_df.columns

Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour', 'year_plane', 'type', 'manufacturer', 'model', 'engines',
       'seats', 'speed', 'engine'],
      dtype='object')

In [24]:
merged_df.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,minute,time_hour,year_plane,type,manufacturer,model,engines,seats,speed,engine
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,15,2013-01-01T10:00:00Z,1999.0,Fixed wing multi engine,BOEING,737-824,2.0,149.0,NaN,Turbo-fan
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,29,2013-01-01T10:00:00Z,1998.0,Fixed wing multi engine,BOEING,737-824,2.0,149.0,NaN,Turbo-fan
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,40,2013-01-01T10:00:00Z,1990.0,Fixed wing multi engine,BOEING,757-223,2.0,178.0,NaN,Turbo-fan
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,45,2013-01-01T10:00:00Z,2012.0,Fixed wing multi engine,AIRBUS,A320-232,2.0,200.0,NaN,Turbo-fan
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,0,2013-01-01T11:00:00Z,1991.0,Fixed wing multi engine,BOEING,757-232,2.0,178.0,NaN,Turbo-fan

## Merge 2: + weather

In [25]:
merged_df.shape

(336776, 27)

In [26]:
weather_df.shape

(26115, 15)

In [27]:
merged_df = pd.merge(
    merged_df,
    weather_df,
    on=["origin", "time_hour"],
    suffixes=["", "_weather"],
    how="left",
)

In [28]:
merged_df.shape

(336776, 40)

## Train-Test-Split

In [29]:
train_df, test_df = train_test_split(merged_df, train_size=.8, random_state=42)

In [30]:
merged_df.shape

(336776, 40)

In [31]:
train_df.shape

(269420, 40)

In [32]:
test_df.shape

(67356, 40)

## Export

In [33]:
train_df.to_pickle(TRAIN_PICKLE)

In [34]:
test_df.to_pickle(TEST_PICKLE)